### ISSUE TITLE
User should be able to find near groups

### ISSUE THREAD

**Issue by fellinga** [fellinga/WalkHealthy#12]
As a user, I want to be able to find a walking group near me, so that I can join that group.

**Comment by JakeGill70** [comment]
What would you think about bumping the point on this one to 3? This is going to take some work with GPS, a lot of searching for typical group meeting locations, and probably some trial and error into finding out what radius is going to be more or less practical for meetups.

**Comment by fellinga** [comment]
Added to Jira
