### ISSUE TITLE
Birthday Validation

### ISSUE THREAD

**Issue by JakeGill70** [fellinga/WalkHealthy#15]
We need to add some additional input validation for birthdays. 
-We need to make sure the month is a valid month (There is no 67th month of the year).
-We need to make sure the day is valid. (No Feb. 30th, and No June 82nd)
-We need to make sure the person is not from the future
-We need to decide on a minimum age to use the app, and make sure the person registering is at least that old.

**Comment by fellinga** [comment]
Added to Jira
