### ISSUE TITLE
User should be able to join groups

### ISSUE THREAD

**Issue by fellinga** [fellinga/WalkHealthy#5]
As a user, I want to be able to join a walking group, so that I can meet like minded people to go on walks with.

**Comment by JakeGill70** [comment]
I think this one is ready to be closed, right?

**Comment by fellinga** [comment]
User are able to create groups at this time but they can not join groups yet (but should be able soon)

**Comment by JakeGill70** [comment]
Gotcha

**Comment by fellinga** [comment]
Added to Jira
